# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "fpm_tools"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "a collection of programs testing fpm(Fortran Package Manager)"

[dev-dependencies]
   M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
   M_time         = { git = "https://github.com/urbanjost/M_time.git" }
   M_io           = { git = "https://github.com/urbanjost/M_io.git" }
   M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
   M_intrinsics   = { git = "https://github.com/urbanjost/M_intrinsics.git" }
   M_escape       = { git = "https://github.com/urbanjost/M_escape.git" }
   M_CLI          = { git = "https://github.com/urbanjost/M_CLI.git" }
   M_CLI2         = { git = "https://github.com/urbanjost/M_CLI2.git" }
   M_history      = { git = "https://github.com/urbanjost/M_history.git" }

#[install]
#library=true

[[executable]]
   name="fpm-f90split"
   source-dir="other/f90split"
   main="f90split.f90"

[[executable]]
   name="fpm-findll"
   source-dir="app"
   main="fpm_findll.f90"

[[executable]]
   name="fpm-fortran"
   source-dir="app"
   main="fpm_intrinsics.f90"
   [executable.dependencies]
   M_intrinsics      = { git = "https://github.com/urbanjost/M_intrinsics.git" }

[[executable]]
   name="fpm-man"
   source-dir="app"
   main="fpm_intrinsics_color.f90"
   [executable.dependencies]
   M_intrinsics  = { git = "https://github.com/urbanjost/M_intrinsics.git" }
   M_escape      = { git = "https://github.com/urbanjost/M_escape.git" }

[[executable]]
   name="fpm-expand"
   source-dir="app"
   main="fpm_expand.f90"
   [executable.dependencies]
   M_CLI      = { git = "https://github.com/urbanjost/M_CLI.git" }

[[executable]]
   name="fpm-bootstrap"
   source-dir="app"
   main="fpm_20201213.f90"
