name = "tmp"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John S. Urban"
#description = "A short project summary in plain text"
#categories = ["fortran", "graphics"]
#keywords = ["hdf5", "mpi"]
#homepage = "https://stdlib.fortran-lang.org"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["ncurses", "sqlite3", "readline", "X11"]
[install]
library = true
