# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "fexpand"
version = "1.0.0"
license = "MIT"
author = "John Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"
description = "expand tabs from files"

[[executable]]
name="fexpand"
source-dir="app"
main="fexpand.f90"

[dependencies.M_CLI2]
git = "https://github.com/urbanjost/M_CLI2.git"

[dependencies.M_io]
git = "https://github.com/urbanjost/M_io.git"
rev = "8cb8bec193e8fd617a9c614df4908f83f32911e6"

[dependencies.M_strings]
git = "https://github.com/urbanjost/M_strings.git"
rev = "ca5b7613a3660506600f00a7a6a834ac0bf50c7c"
